<a href="https://colab.research.google.com/github/GloriaTP/Caso-de-Negocios---Venta-Multicanal---LATAM/blob/main/Copia_de_Sprint07_Webinar11_students_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sprint 7 · Sesión práctica · Proyecto guiado con Python — Versión estudiante

**Duración:** 120 minutos  
**Pausa:** 5 minutos a la mitad  
**Modalidad:** Proyecto práctico guiado en Google Colab  
**Nivel:** Introductorio-intermedio  

En esta sesión vamos a trabajar como analistas de datos de una tienda multicanal LATAM. El objetivo no es memorizar código, sino aprender un flujo de trabajo práctico: cargar datos, explorarlos, limpiarlos, automatizar tareas simples, graficar, detectar outliers, segmentar ventas y cerrar con conclusiones accionables.

## Cómo usar esta versión estudiante

Este notebook está preparado para que tomes apuntes, completes ejercicios y documentes tus decisiones durante la clase.

**Modo de trabajo recomendado:**

1. Lee primero la consigna de cada bloque o ejercicio.
2. Completa los espacios de respuesta antes de comparar con la explicación del instructor/a.
3. Ejecuta las celdas de setup cuando existan.
4. Escribe interpretación, dudas y decisiones en los espacios de apuntes.
5. Al final, revisa si tus respuestas conectan datos, método e implicación de negocio.

> Las salidas de ejecución fueron limpiadas para que puedas correr el notebook desde cero.

## Notas de clase principales

- El proyecto guiado integra carga, exploración, limpieza, automatización, KPIs, visualización y reporte.
- Trabaja de forma incremental: validar, limpiar, calcular, visualizar e interpretar.
- Los ciclos y funciones reducen repetición cuando se revisan varias columnas o reglas.
- Las visualizaciones deben ser consistentes con la pregunta analítica y el tipo de variable.
- El resultado final debe incluir dataset limpio, KPIs principales y conclusiones accionables.

### Mis notas iniciales

-
-
-

## Fecha

Completa la información de la sesión:

- **Fecha: 8/4/2026**  
- **Instructor/a:**  
- **Duración:** 120 minutos  
- **Dataset:** `sprint07_proyecto_ventas_multicanal_latam.csv`

## Objetivos de aprendizaje

Al finalizar la sesión, la persona estudiante podrá:

1. Cargar un archivo `.csv` en Google Colab usando Pandas.
2. Explorar estructura, tipos de datos, valores nulos y métricas descriptivas.
3. Aplicar reglas simples de limpieza sin modificar el dataset original directamente.
4. Usar listas, ciclos `for`, ciclos `while` y funciones pequeñas para automatizar revisiones.
5. Calcular KPIs de negocio con `groupby()`.
6. Crear gráficas sencillas con `.plot()`.
7. Crear gráficas agrupadas con Seaborn usando `hue`.
8. Detectar posibles outliers con la regla IQR.
9. Crear segmentos de venta con funciones y `.apply()`.
10. Comunicar hallazgos con una estructura clara: contexto, hallazgo, evidencia e implicación.

## Agenda sugerida · 120 minutos

| Tiempo | Bloque | Actividad | Modalidad |
|---:|---|---|---|
| 0–10 min | Kickoff | Entender el caso de negocio y las preguntas guía | Discusión rápida |
| 10–20 min | Setup | Preparar Colab, cargar librerías y leer el CSV | Demo guiada |
| 20–35 min | Exploración inicial | `head()`, `shape`, `info()`, nulos y descriptivos | Coding together |
| 35–50 min | Limpieza | Copia segura, normalización de textos e imputaciones simples | Coding together |
| 50–60 min | Automatización | `for`, `while` y funciones pequeñas | Mini-reto guiado |
| 60–65 min | Pausa | Descanso corto | Break |
| 65–80 min | KPIs | Revenue, margen, ticket promedio, devoluciones | Coding together |
| 80–95 min | Visualización | Gráficas con `.plot()` y lectura de patrones | Demo + práctica |
| 95–108 min | Seaborn agrupado | Comparar categorías/canales/tipos de cliente con `hue` | Práctica guiada |
| 108–116 min | Outliers y segmentación | IQR y clasificación de ventas | Reto final |
| 116–120 min | Cierre | Validación, takeaways y canales de ayuda | Plenaria |

## Caso de negocio · Ventas Multicanal LATAM

La empresa vende productos por **Web**, **App**, **Tienda física** y **WhatsApp** en varios países de Latinoamérica. El equipo directivo quiere responder:

- ¿Qué países, canales y categorías generan más ingreso?
- ¿Dónde se concentra el margen?
- ¿Qué segmentos de ventas existen?
- ¿Hay ventas atípicas que puedan distorsionar el análisis?
- ¿Qué visualizaciones ayudan a explicar los hallazgos?

Durante la sesión se irá construyendo una versión limpia del dataset y un pequeño set de hallazgos para presentar al negocio.

## Diccionario de datos

| Columna | Descripción |
|---|---|
| `venta_id` | Identificador único de la venta |
| `fecha` | Fecha de la venta |
| `pais`, `region`, `ciudad` | Ubicación de la operación |
| `canal` | Canal de venta: Web, App, Tienda física o WhatsApp |
| `categoria` | Categoría del producto vendido |
| `metodo_pago` | Medio de pago usado por el cliente |
| `tipo_cliente` | Cliente nuevo o recurrente |
| `unidades` | Cantidad de unidades vendidas |
| `precio_unitario` | Precio unitario antes de descuentos |
| `descuento_pct` | Porcentaje de descuento aplicado |
| `ingreso` | Valor de la venta después del descuento |
| `costo` | Costo estimado de la venta |
| `margen` | Diferencia entre ingreso y costo |
| `edad_cliente` | Edad del cliente |
| `satisfaccion` | Calificación de satisfacción de 1 a 10 |
| `dias_entrega` | Días transcurridos hasta la entrega |
| `devolucion` | Indica si la venta fue devuelta |

## Ejercicio 0 · Kickoff del proyecto \(10 min\)

Antes de ejecutar código, responde en parejas:

1. ¿Cuál sería la métrica principal para medir tamaño de negocio?
- país, región, ciudad
2. ¿Cuál sería la métrica principal para medir rentabilidad?
- margen
3. ¿Qué columnas podrían tener valores nulos?
- metodo_pago, satisfacción, dias_entrega
4. ¿Qué columnas usarías para crear gráficos comparativos?
- ingreso vs pais, región y ciudad, ingresos vs categoría, margen vs categoría
5. ¿Qué parte del proceso parece repetitiva y podría automatizarse?
- limpieza, crear reportes

> **Criterio:** No buscamos una única respuesta correcta. Buscamos justificar qué columna usaríamos y por qué.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

## Preparación del entorno en Google Colab

Google Colab ejecuta Python en la nube. Cada bloque de código se llama **celda**. Para ejecutar una celda puedes usar `Shift + Enter`.

En esta sesión usaremos:

- `pandas` para trabajar con tablas.
- `matplotlib` para gráficas básicas.
- `seaborn` para gráficas agrupadas más legibles.

> Si Colab se desconecta, normalmente basta con volver a ejecutar las celdas desde el inicio.

In [2]:
# ============================================================
# 1. Importar librerías
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

# Configuración visual básica
pd.set_option('display.max_columns', 30)
pd.set_option('display.float_format', '{:,.2f}'.format)
sns.set_theme(style='whitegrid')

print('Librerías cargadas correctamente')

Librerías cargadas correctamente

## Cargar el dataset

Sube el archivo `sprint07_proyecto_ventas_multicanal_latam.csv` a Colab y ejecútalo desde la misma carpeta del notebook.

También podrías cargarlo desde una URL pública de GitHub si luego decides subirlo a un repositorio.

In [3]:
# ============================================================
# 2. Cargar archivo CSV
# ============================================================

archivo = 'https://raw.githubusercontent.com/ljpiere/tpdata_python/refs/heads/main/DA/DA_students/datasets/sprint07_proyecto_ventas_multicanal_latam.csv'

df = pd.read_csv(archivo)

print('Dataset cargado')
print('Filas y columnas:', df.shape)
df.head()

Dataset cargado
Filas y columnas: (180, 19)

,venta_id,fecha,pais,region,ciudad,canal,categoria,metodo_pago,tipo_cliente,unidades,precio_unitario,descuento_pct,ingreso,costo,margen,edad_cliente,satisfaccion,dias_entrega,devolucion
0,V0081,2026-01-26,Colombia,Andina,Barranquilla,Web,Moda,Tarjeta débito,Recurrente,1,"459,000.00",0.25,"344,250.00","265,729.41","78,520.59",28.00,8.00,7.00,No
1,V0143,2026-03-11,Chile,Cono Sur,Valparaíso,Web,Deportes,Efectivo,Nuevo,3,"776,000.00",0.00,"2,328,000.00","1,805,865.88","522,134.12",30.00,7.00,2.00,No
2,V0077,2026-04-01,Colombia,Andina,Cali,Tienda física,Hogar,Tarjeta crédito,Nuevo,2,"190,000.00",0.15,"323,000.00","209,542.41","113,457.59",56.00,6.00,3.00,No
3,V0156,2026-01-19,Colombia,Andina,Medellín,Web,Belleza,Tarjeta débito,Nuevo,2,"70,000.00",0.05,"133,000.00","86,706.30","46,293.70",27.00,7.00,6.00,No
4,V0087,2026-02-18,Perú,Andina,Arequipa,Web,Moda,Tarjeta crédito,Nuevo,1,"82,000.00",0.05,"77,900.00","43,196.02","34,703.98",50.00,8.00,3.00,No

## Ejercicio 1 · Primer vistazo al dataset \(15 min\)

Tareas:

1. Mostrar las primeras filas.
2. Revisar cantidad de filas y columnas.
3. Listar nombres de columnas.
4. Revisar tipos de datos.
5. Identificar columnas numéricas y categóricas.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [4]:
# Mostrar las primeras filas.
print(df.head())

  venta_id       fecha      pais    region        ciudad          canal  \
0    V0081  2026-01-26  Colombia    Andina  Barranquilla            Web
1    V0143  2026-03-11     Chile  Cono Sur    Valparaíso            Web
2    V0077  2026-04-01  Colombia    Andina          Cali  Tienda física
3    V0156  2026-01-19  Colombia    Andina      Medellín            Web
4    V0087  2026-02-18      Perú    Andina      Arequipa            Web

  categoria      metodo_pago tipo_cliente  unidades  precio_unitario  \
0      Moda   Tarjeta débito   Recurrente         1       459,000.00
1  Deportes         Efectivo        Nuevo         3       776,000.00
2     Hogar  Tarjeta crédito        Nuevo         2       190,000.00
3   Belleza   Tarjeta débito        Nuevo         2        70,000.00
4      Moda  Tarjeta crédito        Nuevo         1        82,000.00

   descuento_pct      ingreso        costo     margen  edad_cliente  \
0           0.25   344,250.00   265,729.41  78,520.59         28.00
1           0.00 2,328,000.00 1,805,865.88 522,134.12         30.00
2           0.15   323,000.00   209,542.41 113,457.59         56.00
3           0.05   133,000.00    86,706.30  46,293.70         27.00
4           0.05    77,900.00    43,196.02  34,703.98         50.00

   satisfaccion  dias_entrega devolucion
0          8.00          7.00         No
1          7.00          2.00         No
2          6.00          3.00         No
3          7.00          6.00         No
4          8.00          3.00         No

In [5]:
# Revisar cantidad de filas y columnas.
print(df.shape)

(180, 19)

In [6]:
# Listar nombres de columnas.
print('Filas y Columnas:', df.columns.to_list)

Filas y Columnas: <bound method IndexOpsMixin.tolist of Index(['venta_id', 'fecha', 'pais', 'region', 'ciudad', 'canal', 'categoria',
       'metodo_pago', 'tipo_cliente', 'unidades', 'precio_unitario',
       'descuento_pct', 'ingreso', 'costo', 'margen', 'edad_cliente',
       'satisfaccion', 'dias_entrega', 'devolucion'],
      dtype='object')>

In [65]:
# Identificar columnas numéricas y categóricas.
columna_numericas = df.select_dtypes(include="number").columns.to_list
columna_categoricas = df.select_dtypes(include="object").columns.to_list
print(columna_numericas, columna_categoricas)

<bound method IndexOpsMixin.tolist of Index(['unidades', 'precio_unitario', 'descuento_pct', 'ingreso', 'costo',
       'margen', 'edad_cliente', 'satisfaccion', 'dias_entrega'],
      dtype='object')> <bound method IndexOpsMixin.tolist of Index(['venta_id', 'fecha', 'pais', 'region', 'ciudad', 'canal', 'categoria',
       'metodo_pago', 'tipo_cliente', 'devolucion'],
      dtype='object')>

## Ejercicio 2 · Revisión de valores nulos \(10 min\)

Tareas:

1. Contar nulos por columna.
2. Calcular el porcentaje de nulos.
3. Decidir qué columnas requieren limpieza.

> Para una primera práctica, usaremos reglas simples. En proyectos reales, la decisión debe validarse con negocio o con la fuente de datos.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [8]:
# Contar nulos por columna y porcentaje
nulos = pd.DataFrame({
    "nulos":      df.isna().sum(),
    "porcentaje": df.isna().mean() * 100
}).sort_values("nulos", ascending = False)
#nulos = df.isna().sum()
#print("nulos", nulos)
#porcentaje = df.isna().mean() * 100
#print("porcentaje", porcentaje)
print(nulos)

                 nulos  porcentaje
metodo_pago         11        6.11
satisfaccion         9        5.00
dias_entrega         7        3.89
edad_cliente         5        2.78
pais                 0        0.00
venta_id             0        0.00
fecha                0        0.00
categoria            0        0.00
region               0        0.00
canal                0        0.00
ciudad               0        0.00
precio_unitario      0        0.00
unidades             0        0.00
tipo_cliente         0        0.00
descuento_pct        0        0.00
margen               0        0.00
costo                0        0.00
ingreso              0        0.00
devolucion           0        0.00

Los datos que requieren limpiza son metodo_pago, satisfaccion, dias_entrega, edad_cliente

## Ejercicio 3 · Crear una copia limpia \(15 min\)

Regla de trabajo: no modificamos el dataset original directamente. Creamos `df_limpio` para preservar la trazabilidad.

Aplicaremos cuatro decisiones:

1. Convertir `fecha` a tipo fecha.
2. Normalizar textos en `canal`.
3. Completar `metodo_pago` con `No informado`.
4. Completar variables numéricas con la mediana.

In [48]:
# Crear una copia limpia
df_limpio = df.copy()

In [49]:
# Converti fecha
df_limpio["fecha"] = pd.to_datetime(df_limpio["fecha"])

In [50]:
# Normalizar textos en canal.
lista_caracteres = ("pais", "region", "ciudad", "canal", "categoria", "metodo_pago", "tipo_cliente", "devolucion")
for col in lista_caracteres:
  df_limpio[col] = df_limpio[col].astype("string").str.strip().str.title()
df_limpio.head()

,venta_id,fecha,pais,region,ciudad,canal,categoria,metodo_pago,tipo_cliente,unidades,precio_unitario,descuento_pct,ingreso,costo,margen,edad_cliente,satisfaccion,dias_entrega,devolucion
0,V0081,2026-01-26,Colombia,Andina,Barranquilla,Web,Moda,Tarjeta Débito,Recurrente,1,"459,000.00",0.25,"344,250.00","265,729.41","78,520.59",28.00,8.00,7.00,No
1,V0143,2026-03-11,Chile,Cono Sur,Valparaíso,Web,Deportes,Efectivo,Nuevo,3,"776,000.00",0.00,"2,328,000.00","1,805,865.88","522,134.12",30.00,7.00,2.00,No
2,V0077,2026-04-01,Colombia,Andina,Cali,Tienda Física,Hogar,Tarjeta Crédito,Nuevo,2,"190,000.00",0.15,"323,000.00","209,542.41","113,457.59",56.00,6.00,3.00,No
3,V0156,2026-01-19,Colombia,Andina,Medellín,Web,Belleza,Tarjeta Débito,Nuevo,2,"70,000.00",0.05,"133,000.00","86,706.30","46,293.70",27.00,7.00,6.00,No
4,V0087,2026-02-18,Perú,Andina,Arequipa,Web,Moda,Tarjeta Crédito,Nuevo,1,"82,000.00",0.05,"77,900.00","43,196.02","34,703.98",50.00,8.00,3.00,No

In [53]:
# Completar metodo_pago con No informado.
df_limpio["metodo_pago"] = df_limpio["metodo_pago"].fillna("No informado")
#print(df_limpio["metodo_pago"].isna().sum())

0

In [62]:
# Completar variables numéricas con la mediana.
#mediana_diasentrega = df_limpio["dias_entrega"].median()
#mediana_edadcliente = df_limpio["edad_cliente"].median()
lista_cambios = ("dias_entrega", "edad_cliente", "satisfaccion")
for col in lista_cambios:
  mediana_col = df_limpio[col].median()
  df_limpio[col] = df_limpio[col].fillna(mediana_col)

In [63]:
# Validación de resultados
nulos = pd.DataFrame({
    "nulos":      df_limpio.isna().sum(),
    "porcentaje": df_limpio.isna().mean() * 100
}).sort_values("nulos", ascending = False)
print(nulos)
#print(df_limpio["metodo_pago"].isna().sum())

                 nulos  porcentaje
venta_id             0        0.00
fecha                0        0.00
pais                 0        0.00
region               0        0.00
ciudad               0        0.00
canal                0        0.00
categoria            0        0.00
metodo_pago          0        0.00
tipo_cliente         0        0.00
unidades             0        0.00
precio_unitario      0        0.00
descuento_pct        0        0.00
ingreso              0        0.00
costo                0        0.00
margen               0        0.00
edad_cliente         0        0.00
satisfaccion         0        0.00
dias_entrega         0        0.00
devolucion           0        0.00

## Ejercicio 4 · Automatización con `for`, `while` y funciones \(10 min\)

En análisis de datos hay tareas repetitivas: revisar varias columnas, calcular varios resúmenes o generar varios gráficos. Para eso usamos automatización básica.

Primero recorreremos columnas numéricas con `for`.

In [71]:
columnas = df.select_dtypes(include="number").columns
for col in columnas:
  media = df_limpio[col].mean()
  mediana = df_limpio[col].median()
  min = df_limpio[col].min()
  max = df_limpio[col].max()
  print("valores de", col, ":", media, mediana, min, max)

valores de unidades : 1.8388888888888888 1.0 1 15
valores de precio_unitario : 805183.3333333334 522000.0 49000.0 2942000.0
valores de descuento_pct : 0.09194444444444443 0.1 0.0 0.25
valores de ingreso : 1309338.7777777778 685600.0 45600.0 9770400.0
valores de costo : 852555.4916111112 451028.93000000005 23964.17 6621546.86
valores de margen : 456783.2861666666 239244.505 14264.88 4376769.0
valores de edad_cliente : 35.01111111111111 34.0 18.0 62.0
valores de satisfaccion : 7.433333333333334 8.0 2.0 10.0
valores de dias_entrega : 4.122222222222222 4.0 1.0 24.0

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# Automatización con Funcion

# Pausa · 5 minutos

Antes de seguir, verifica que tienes creadas estas variables:

- `df`
- `df_limpio`
- `columnas_revision`
- `resumen_numerico`

Después de la pausa, pasamos de preparación de datos a análisis de negocio y visualización.

## Ejercicio 5 · KPIs del proyecto \(15 min\)

Vamos a calcular métricas que el negocio podría usar:

- Ingreso total.
- Margen total.
- Margen porcentual.
- Ticket promedio.
- Tasa de devolución.
- Satisfacción promedio.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# KPIs Generales

## Ejercicio 6 · Gráficas sencillas con `.plot()` \(15 min\)

`.plot()` es una forma simple de crear visualizaciones directamente desde Pandas. Es ideal para empezar porque se conecta fácil con `groupby()`.

Crearemos:

1. Barras de ingreso por país.
2. Barras horizontales de ingreso por categoría.
3. Línea de ingreso por mes.
4. Histograma de ingresos.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# Barras de ingreso por pais

In [ ]:
# Barras horizontales de ingreso por categoría

In [ ]:
# Línea de ingreso por mes.

In [ ]:
# Histograma de Ingresos

## Ejercicio 7 · Gráficas agrupadas con Seaborn \(13 min\)

Seaborn permite comparar grupos de forma más clara usando argumentos como `hue`.

Crearemos:

1. Ingreso total por categoría separado por canal.
2. Margen porcentual por canal separado por tipo de cliente.
3. Distribución de ingresos por canal y tipo de cliente.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# Ingreso total por categoría separado por canal

In [ ]:
# Margen porcentual por canal separado por tipo de cliente.
# Ingreso total por categoría separado por canal

In [ ]:
# Distribución de ingresos por canal y tipo de cliente.

## Ejercicio 8 · Outliers con IQR \(8 min\)

La regla IQR permite detectar valores inusualmente altos o bajos.

No significa que esos valores estén mal. Significa que deben revisarse antes de sacar conclusiones.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# TODO estudiante: escribe aquí tu código.
# Función para calcular límites IQR

In [ ]:
# Indentificar Ventas Atípicas por Ingreso

## Ejercicio 9 · Segmentación de ventas \(8 min\)

Segmentar ayuda a convertir números en etiquetas interpretables. Vamos a clasificar cada venta por tamaño de ingreso.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# Función para segmentación

In [ ]:
# Conteo por Segmento

## Ejercicio 10 · Reto final del proyecto \(8 min\)

Construye una tabla final con una recomendación de negocio.

Tarea:

1. Agrupa por `pais`, `canal` y `categoria`.
2. Calcula ingreso total, margen total, cantidad de ventas y margen porcentual.
3. Ordena de mayor a menor ingreso.
4. Selecciona los 10 primeros registros.
5. Escribe una conclusión usando esta estructura:

> En `[país/canal/categoría]` se observa `[hallazgo]`, porque `[evidencia]`. Esto sugiere `[acción o pregunta de negocio]`.

### Espacio de trabajo del estudiante

**Mi interpretación de la consigna:**  

**Mi procedimiento / fórmula / consulta:**  

**Resultado obtenido:**  

**Conclusión breve:**

In [ ]:
# Tabla final para recomendación

In [ ]:
# Exportar resultados principales

## Estructura sugerida para GitHub

```text
sprint07-proyecto-ventas-python/
├── data/
│   ├── sprint07_proyecto_ventas_multicanal_latam.csv
│   └── sprint07_ventas_multicanal_limpio.csv
├── notebooks/
│   └── Sprint07_Sesion_Unica_Proyecto_Practico_120min_Python.ipynb
├── outputs/
│   └── sprint07_ranking_final_ventas.csv
└── README.md
```

### README mínimo

```markdown
# Sprint 7 · Proyecto de ventas multicanal LATAM

## Objetivo
Analizar ventas, margen, canales, categorías, outliers y segmentos usando Python.

## Herramientas
Google Colab, Python, Pandas, Matplotlib y Seaborn.

## Pasos principales
1. Cargar datos.
2. Explorar estructura y calidad.
3. Limpiar valores nulos y textos.
4. Calcular KPIs.
5. Visualizar con Pandas y Seaborn.
6. Detectar outliers.
7. Segmentar ventas.
8. Comunicar hallazgos.
```

## Preguntas de validación de conocimiento

Responde individualmente y luego valida en plenaria:

1. ¿Por qué creamos `df_limpio = df.copy()` antes de limpiar?
2. ¿Qué diferencia hay entre `df.head()` y `df.info()`?
3. ¿Para qué sirve `groupby()` en un análisis de negocio?
4. ¿Qué ventaja tiene usar un ciclo `for` al revisar varias columnas?
5. ¿Qué problema puede ocurrir si eliminamos outliers sin analizarlos?
6. ¿Qué aporta Seaborn frente a una gráfica básica con `.plot()`?
7. ¿Qué significa usar `hue` en una gráfica de Seaborn?
8. ¿Qué archivo exportamos al final y para qué serviría?

### Mis respuestas

> Escribe aquí tus respuestas antes de la discusión en clase.

1.
2.
3.

### Mis respuestas de validación

1.  
2.  
3.  

**Tema que necesito repasar:**

## Takeaways

- Un proyecto de análisis necesita orden: cargar, explorar, limpiar, analizar, visualizar y comunicar.
- `df.copy()` ayuda a trabajar de forma segura sin perder el dataset original.
- Los valores nulos no siempre se eliminan; también pueden imputarse o marcarse.
- `for`, `while` y funciones pequeñas ayudan a reducir código repetido.
- `groupby()` conecta Python con preguntas de negocio.
- `.plot()` es suficiente para visualizaciones rápidas y claras.
- Seaborn permite comparar grupos con mayor facilidad usando `hue`.
- Los outliers deben investigarse antes de tomar decisiones sobre ellos.
- Una buena conclusión combina hallazgo, evidencia e implicación.

### Mis respuestas de validación

1.  
2.  
3.  

**Tema que necesito repasar:**

## Cierre

Pregunta final para discusión:

> Si tuvieras que presentar solo un hallazgo de este proyecto al negocio, ¿cuál elegirías y qué gráfica usarías para defenderlo?

Cierre sugerido:

1. Compartir una tabla o gráfica final.
2. Explicar un hallazgo con evidencia.
3. Proponer una acción o siguiente análisis.
4. Guardar el notebook y los archivos generados.

## Canales de ayuda

Para resolver dudas después de la sesión, usa los canales definidos por el programa:

- Canal de preguntas de la cohorte.
- Espacios de tutoría o mentoría.
- Revisión entre pares.
- Documentación oficial de Pandas, Matplotlib y Seaborn.
- Comentarios dentro del notebook para explicar decisiones de limpieza o análisis.

Cuando pidas ayuda, intenta incluir:

1. Qué querías hacer.
2. Qué código ejecutaste.
3. Qué error o resultado obtuviste.
4. Qué intentaste revisar antes de preguntar.

## Información complementaria

Temas sugeridos para practicar después:

- Crear una nueva columna `rentabilidad` con reglas de negocio.
- Comparar ventas con y sin devolución.
- Crear una gráfica agrupada por `pais` y `tipo_cliente`.
- Cambiar los límites de segmentación y comparar resultados.
- Crear una función que reciba una columna y genere automáticamente una gráfica.
- Publicar el notebook y el dataset en GitHub con un README claro.